import Link from "next/link";
import "../styles/globals.css"

export const metadata = {
  title: "Ash's Blog",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header className="text-center bg-gradient-to-b from-blue-700 via-blue-800 to-gray-900 p-6 my-6 rounded-md">
      <div>
      <Link href="/">
        <h1 className="text-3xl font-bold text-white">Ash with Bash</h1>
      </Link>
      <p>Ash's Online NootBook here. 📒</p>
      </div>
  </header>
  );
  
  const footer = (
    <footer>
      <div className="border-t border-slate-800 mt-6 py-6  text-slate-600 text-center">
        <h3>Developed by Ash's trash</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
        
      </body>
    </html>
  )
}
